### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by amphilagus** [N-Medvedev/TREKIS-3#1]
#### Environment(for bug reports)
- [x] Operating System: Ubuntu 20.04.4 LTS  
- [x] compiler version: ifort 2021.6.0  
#### Steps to Reproduce the Issue
./Makefile
#### Current Result (Include screenshots where appropriate.)
ifort: command line remark #10148: option '-vec-report0' not supported  
ifort: command line warning #10006: ignoring unknown option '-real-siz'  
ifort: error #10236: File not found:  '64'

**Comment by N-Medvedev** [comment]
Thank you. The syntax in Makefile was updated.
